### ISSUE TITLE
Url encode add "+" instead of " " in card owner name

### ISSUE THREAD

**Issue by jigarsangoi** [landlogicit/gestpay-for-nopcommerce#2]
Hello,
when we are using prefessional package of GestPay. In that you guys encodes Buyer's name which result into card holder name on payment page like this "Firstname+Lastname" instead of "Firstname Lastname".

Also in report in gestpay dashboard it shows buyer's name like "Firstname+Lastname" due to encoding

**Comment by landlogicit** [comment]
Thanks for your debug. Now i will check your code for testing sandbox url.
